extends Node3D

signal sector_load_requested(sector_id: StringName)
signal sector_loaded(sector_id: StringName)
signal sector_unloaded(sector_id: StringName)
signal sector_state_changed(sector_id: StringName)

const PLAYER_GROUP := &"player"
const WAVE_MANAGER_GROUP := &"wave_manager"
const CAMP_ECONOMY_GROUP := &"camp_economy"
const EAST_SECTOR_ID := &"east"
const EAST_SECTOR_SCENE_PATH := "res://scenes/world/sectors/east_sector.tscn"
const AMBUSH_TRIGGER_DISTANCE := 30.0

## Compact open world grid: 4 x 4 sectors of 64 x 64 m (256 x 256 m total).
## The camp sector (0, 0) stays inside the persistent arena scene, the east
## sector (1, 0) is hand-made, and every other chunk is generated by seed.
const SECTOR_SIZE := 64.0
const GRID_MIN := Vector2i(-1, -1)
const GRID_MAX := Vector2i(2, 2)
const CAMP_COORDS := Vector2i(0, 0)
const EAST_COORDS := Vector2i(1, 0)

# Sectors load well before they come into view (roughly a sector and a half
# away) so the staged generation finishes off-screen and there is no visible
# pop-in or delay when the player arrives.
@export_range(8.0, 200.0, 1.0) var load_distance: float = 95.0
@export_range(8.0, 240.0, 1.0) var unload_distance: float = 120.0

var _player: Node3D
var _run_seed: int = randi()
var _definitions_by_id: Dictionary[StringName, Dictionary] = {}
var _instances: Dictionary[StringName, Node3D] = {}
var _request_started_ticks: Dictionary[StringName, int] = {}
var _sector_states: Dictionary[StringName, Dictionary] = {}
var _beacon_activated: Dictionary[StringName, bool] = {}


func _ready() -> void:
	if unload_distance <= load_distance:
		push_error("WorldStreamer unload distance must be greater than its load distance.")
	_build_grid_definitions()
	call_deferred(&"_find_player")


func _physics_process(_delta: float) -> void:
	if not is_instance_valid(_player):
		_find_player()
	if not is_instance_valid(_player):
		return
	for sector_id in _definitions_by_id:
		var definition: Dictionary = _definitions_by_id[sector_id]
		var distance := _player.global_position.distance_to(
			Vector3(definition["position"])
		)
		if distance <= load_distance:
			request_sector_load(sector_id)
		elif distance >= unload_distance:
			unload_sector(sector_id)
	_poll_pending_requests()
	_update_sector_ambushes()


func request_sector_load(sector_id: StringName) -> bool:
	if _instances.has(sector_id) or _request_started_ticks.has(sector_id):
		return false
	var definition := _get_definition(sector_id)
	if definition.is_empty():
		return false
	if String(definition["kind"]) == "scene":
		var request_error := ResourceLoader.load_threaded_request(
			String(definition["scene_path"])
		)
		if request_error != OK:
			push_error(
				"WorldStreamer could not request sector '%s': %s"
				% [sector_id, request_error]
			)
			return false
		_request_started_ticks[sector_id] = Time.get_ticks_msec()
		sector_load_requested.emit(sector_id)
		return true
	sector_load_requested.emit(sector_id)
	_generate_sector(sector_id, definition)
	return true


func unload_sector(sector_id: StringName) -> bool:
	# A background request in flight cannot be cancelled; dropping the entry
	# makes the result be discarded once it finishes.
	_request_started_ticks.erase(sector_id)
	if not _instances.has(sector_id):
		return false
	var sector: Node3D = _instances[sector_id]
	_instances.erase(sector_id)
	if is_instance_valid(sector):
		remove_child(sector)
		sector.queue_free()
	sector_unloaded.emit(sector_id)
	return true


func is_sector_loaded(sector_id: StringName) -> bool:
	return _instances.has(sector_id) and is_instance_valid(_instances[sector_id])


func get_sector(sector_id: StringName) -> Node3D:
	if is_sector_loaded(sector_id):
		return _instances[sector_id]
	return null


func get_loaded_sector_count() -> int:
	var count := 0
	for sector_id in _instances:
		if is_instance_valid(_instances[sector_id]):
			count += 1
	return count


func get_sector_state(sector_id: StringName) -> Dictionary:
	return _sector_states.get(sector_id, {})


func is_east_sector_loaded() -> bool:
	return is_sector_loaded(EAST_SECTOR_ID)


func get_east_sector() -> Node3D:
	return get_sector(EAST_SECTOR_ID)


func is_east_beacon_activated() -> bool:
	return bool(_beacon_activated.get(EAST_SECTOR_ID, false))


func _build_grid_definitions() -> void:
	for grid_x in range(GRID_MIN.x, GRID_MAX.x + 1):
		for grid_z in range(GRID_MIN.y, GRID_MAX.y + 1):
			var coords := Vector2i(grid_x, grid_z)
			if coords == CAMP_COORDS:
				continue
			var sector_position := Vector3(
				coords.x * SECTOR_SIZE, 0.0, coords.y * SECTOR_SIZE
			)
			if coords == EAST_COORDS:
				_definitions_by_id[EAST_SECTOR_ID] = {
					"id": EAST_SECTOR_ID,
					"kind": "scene",
					"scene_path": EAST_SECTOR_SCENE_PATH,
					"position": sector_position,
					"coords": coords,
				}
				continue
			var sector_id := StringName("sector_%d_%d" % [coords.x, coords.y])
			_definitions_by_id[sector_id] = {
				"id": sector_id,
				"kind": "generated",
				"position": sector_position,
				"coords": coords,
			}


func _generate_sector(sector_id: StringName, definition: Dictionary) -> void:
	# Generation is spread over several frames: the shell appears immediately
	# and each road quadrant, the content and the navigation land on their own
	# frame, so no single frame pays the full ~140 ms cost.
	var start_ticks := Time.get_ticks_usec()
	var state := _get_or_create_sector_state(sector_id, definition)
	var coords: Vector2i = definition["coords"]
	var context := SectorGenerator.begin_sector({
		"id": sector_id,
		"seed": int(state["seed"]),
		"collected_caches": state["collected_caches"],
		"ammo_collected": bool(state.get("ammo_collected", false)),
		"outer_walls": _get_outer_wall_sides(coords),
		"label": "SECTOR %d · %d" % [coords.x, coords.y],
		"weapon_collected": bool(state.get("weapon_collected", false)),
		"cache_collected_callable": _on_sector_cache_collected,
		"ammo_collected_callable": _on_sector_ammo_collected,
		"weapon_collected_callable": _on_sector_weapon_collected,
	})
	var sector: Node3D = context["sector"]
	sector.position = Vector3(definition["position"])
	add_child(sector)
	_instances[sector_id] = sector
	for quadrant_index in 4:
		await get_tree().process_frame
		if not _is_generation_still_valid(sector_id, sector):
			return
		SectorGenerator.add_roads_stage(context, quadrant_index)
	await get_tree().process_frame
	if not _is_generation_still_valid(sector_id, sector):
		return
	SectorGenerator.add_content_stage(context)
	await get_tree().process_frame
	if not _is_generation_still_valid(sector_id, sector):
		return
	SectorGenerator.finish_sector(context)
	var elapsed_ms := (Time.get_ticks_usec() - start_ticks) / 1000.0
	print(
		"WorldStreamer: sector '%s' generated over frames in %.1f ms total (seed %d)."
		% [sector_id, elapsed_ms, int(state["seed"])]
	)
	sector_loaded.emit(sector_id)


func _is_generation_still_valid(sector_id: StringName, sector: Node3D) -> bool:
	return is_instance_valid(sector) and _instances.get(sector_id) == sector


func _get_or_create_sector_state(
	sector_id: StringName, definition: Dictionary
) -> Dictionary:
	if not _sector_states.has(sector_id):
		var coords: Vector2i = definition["coords"]
		_sector_states[sector_id] = {
			"seed": hash([_run_seed, coords.x, coords.y]) & 0x7FFFFFFF,
			"collected_caches": [],
			"ammo_collected": false,
			"weapon_collected": false,
			"ambush_triggered": false,
		}
	return _sector_states[sector_id]


func _get_outer_wall_sides(coords: Vector2i) -> Array[StringName]:
	var sides: Array[StringName] = []
	if coords.x - 1 < GRID_MIN.x:
		sides.append(&"west")
	if coords.x + 1 > GRID_MAX.x:
		sides.append(&"east")
	if coords.y - 1 < GRID_MIN.y:
		sides.append(&"north")
	if coords.y + 1 > GRID_MAX.y:
		sides.append(&"south")
	return sides


func _on_sector_cache_collected(sector_id: StringName, cache_index: int) -> void:
	if not _sector_states.has(sector_id):
		return
	var collected: Array = _sector_states[sector_id]["collected_caches"]
	if cache_index not in collected:
		collected.append(cache_index)
	sector_state_changed.emit(sector_id)


func _on_sector_ammo_collected(sector_id: StringName) -> void:
	if not _sector_states.has(sector_id):
		return
	_sector_states[sector_id]["ammo_collected"] = true
	sector_state_changed.emit(sector_id)


func _on_sector_weapon_collected(sector_id: StringName) -> void:
	if not _sector_states.has(sector_id):
		return
	_sector_states[sector_id]["weapon_collected"] = true
	sector_state_changed.emit(sector_id)


func _update_sector_ambushes() -> void:
	for sector_id in _instances:
		var definition: Dictionary = _definitions_by_id.get(sector_id, {})
		if definition.is_empty() or String(definition["kind"]) != "generated":
			continue
		var state: Dictionary = _sector_states.get(sector_id, {})
		if state.is_empty() or bool(state.get("ambush_triggered", false)):
			continue
		var distance := _player.global_position.distance_to(
			Vector3(definition["position"])
		)
		if distance > AMBUSH_TRIGGER_DISTANCE:
			continue
		if _try_spawn_sector_ambush(sector_id, state):
			state["ambush_triggered"] = true
			sector_state_changed.emit(sector_id)


func _try_spawn_sector_ambush(sector_id: StringName, state: Dictionary) -> bool:
	var wave_manager := get_tree().get_first_node_in_group(WAVE_MANAGER_GROUP)
	if (
		wave_manager == null
		or not wave_manager.has_method(&"spawn_exploration_enemies")
		or not bool(wave_manager.call(&"is_preparation_active"))
	):
		return false
	var sector := get_sector(sector_id)
	if sector == null:
		return false
	var spawns_root := sector.get_node_or_null("SpawnPoints")
	if spawns_root == null:
		return false
	var markers: Array[Marker3D] = []
	for child in spawns_root.get_children():
		var marker := child as Marker3D
		if marker != null:
			markers.append(marker)
	if markers.is_empty():
		return false
	var ambush_seed := int(state["seed"])
	var runner_count := ambush_seed % 2
	var normal_markers := markers.slice(0, markers.size() - runner_count)
	var runner_markers := markers.slice(markers.size() - runner_count)
	var spawned_enemies: Array = []
	if not normal_markers.is_empty():
		spawned_enemies.append_array(wave_manager.call(
			&"spawn_exploration_enemies",
			wave_manager.get(&"normal_zombie_scene"),
			normal_markers
		))
	if not runner_markers.is_empty():
		spawned_enemies.append_array(wave_manager.call(
			&"spawn_exploration_enemies",
			wave_manager.get(&"runner_zombie_scene"),
			runner_markers
		))
	if spawned_enemies.is_empty():
		return false
	var camp_economy := get_tree().get_first_node_in_group(CAMP_ECONOMY_GROUP)
	if camp_economy != null and camp_economy.has_method(&"request_feedback"):
		var coords: Vector2i = _definitions_by_id[sector_id]["coords"]
		camp_economy.call(
			&"request_feedback",
			"AMBUSH IN SECTOR %d · %d" % [coords.x, coords.y]
		)
	return true


func _poll_pending_requests() -> void:
	for sector_id in _request_started_ticks.keys():
		var definition := _get_definition(sector_id)
		var scene_path := String(definition["scene_path"])
		var status := ResourceLoader.load_threaded_get_status(scene_path)
		match status:
			ResourceLoader.THREAD_LOAD_IN_PROGRESS:
				continue
			ResourceLoader.THREAD_LOAD_LOADED:
				var elapsed_ms := (
					Time.get_ticks_msec() - int(_request_started_ticks[sector_id])
				)
				_request_started_ticks.erase(sector_id)
				var sector_scene := ResourceLoader.load_threaded_get(scene_path) as PackedScene
				_instantiate_scene_sector(sector_id, definition, sector_scene, elapsed_ms)
			_:
				_request_started_ticks.erase(sector_id)
				push_error(
					"WorldStreamer failed to load sector '%s' (status %d)." % [sector_id, status]
				)


func _instantiate_scene_sector(
	sector_id: StringName,
	definition: Dictionary,
	sector_scene: PackedScene,
	elapsed_ms: int
) -> void:
	if sector_scene == null:
		push_error("WorldStreamer received an empty scene for sector '%s'." % sector_id)
		return
	var sector := sector_scene.instantiate() as Node3D
	if sector == null:
		push_error("WorldStreamer sector scenes must use a Node3D root.")
		return
	sector.name = String(sector_id).to_pascal_case() + "Sector"
	sector.position = Vector3(definition["position"])
	add_child(sector)
	_instances[sector_id] = sector
	if sector_id == EAST_SECTOR_ID:
		_configure_east_beacon(sector)
	print("WorldStreamer: sector '%s' ready in %d ms (background)." % [sector_id, elapsed_ms])
	sector_loaded.emit(sector_id)


func _get_definition(sector_id: StringName) -> Dictionary:
	if not _definitions_by_id.has(sector_id):
		push_error("WorldStreamer has no sector definition for '%s'." % sector_id)
		return {}
	return _definitions_by_id[sector_id]


func _find_player() -> void:
	_player = get_tree().get_first_node_in_group(PLAYER_GROUP) as Node3D


func _configure_east_beacon(sector: Node3D) -> void:
	var beacon := sector.get_node_or_null("%ExpeditionBeacon") as Area3D
	if beacon == null or not beacon.has_method(&"configure"):
		push_error("East sector requires a unique ExpeditionBeacon node.")
		return
	beacon.call(&"configure", is_east_beacon_activated())
	beacon.connect(&"activated", _on_east_beacon_activated)


func _on_east_beacon_activated() -> void:
	if is_east_beacon_activated():
		return
	_beacon_activated[EAST_SECTOR_ID] = true
	sector_state_changed.emit(EAST_SECTOR_ID)
