class_name WorldStreamer
extends Node3D

signal sector_load_requested(sector_id: StringName)
signal sector_loaded(sector_id: StringName)
signal sector_unloaded(sector_id: StringName)
signal sector_state_changed(sector_id: StringName)

const PLAYER_GROUP := &"player"
const WAVE_MANAGER_GROUP := &"wave_manager"
const CAMP_ECONOMY_GROUP := &"camp_economy"
const AMBUSH_TRIGGER_DISTANCE := 30.0
const SECTOR_NODES_PER_FRAME := 5

## Open world grid. The camp sector stays inside the persistent arena scene;
## every other chunk is generated by seed.
const SECTOR_SIZE := 64.0
## 8 x 8 sectors of 64 m: a 512 m world. Big enough to feel like somewhere, small
## enough that a player can push out and still make the extraction inside the
## run's ten minutes.
const GRID_MIN := Vector2i(-3, -3)
const GRID_MAX := Vector2i(4, 4)
## Which sector holds the camp. Off-centre on purpose: dead centre makes every
## run the same shape, out and back along a radius, with no side of the map
## more dangerous than any other. Must match tools/place_camp.CAMP_COORDS and
## tools/paint_world.CENTRE.
const CAMP_COORDS := Vector2i(-1, -1)

# Load the current sector plus its orthogonal neighbours (a sector centre is
# 64 m away). 72 m keeps roughly five sectors resident instead of nine, which
# cuts draw calls a lot in the GL Compatibility renderer while still loading a
# sector before the player reaches it. Diagonals stream in as you approach.
@export_range(8.0, 200.0, 1.0) var load_distance: float = 72.0
@export_range(8.0, 240.0, 1.0) var unload_distance: float = 96.0

var _player: Node3D
# Drawn from the save on ready: the layout is stable across runs per profile.
var _run_seed: int = 0
# Last sector build/load time in milliseconds, surfaced by the FPS overlay.
var last_build_ms: float = 0.0
var _definitions_by_id: Dictionary[StringName, Dictionary] = {}
var _instances: Dictionary[StringName, Node3D] = {}
var _request_started_ticks: Dictionary[StringName, int] = {}
var _sector_states: Dictionary[StringName, Dictionary] = {}
# Sector ambushes re-arm once per horde cycle, so revisiting or holding a sector
# across cycles keeps producing encounters instead of a single one per run.
var _cycle_connected: bool = false
# Generated sectors are built on worker threads so the heavy node construction
# never hitches the main thread; results are added to the tree once ready.
var _generation_tasks: Dictionary[StringName, int] = {}
var _generation_meta: Dictionary[StringName, Dictionary] = {}
var _generation_results: Dictionary[StringName, Node3D] = {}
var _generation_mutex := Mutex.new()
# Adding a finished sector in one go costs hundreds of ms on the main thread
# (every mesh, body and nav region registers at once). The subtree is therefore
# detached and re-attached a few nodes per frame.
var _pending_attachments: Dictionary[StringName, Array] = {}


func _ready() -> void:
	if unload_distance <= load_distance:
		push_error("WorldStreamer unload distance must be greater than its load distance.")
	_run_seed = SaveManager.ensure_world_seed()
	_build_grid_definitions()
	call_deferred(&"_find_player")


func _physics_process(_delta: float) -> void:
	if not is_instance_valid(_player):
		_find_player()
	if not is_instance_valid(_player):
		return
	for sector_id in _definitions_by_id:
		var definition: Dictionary = _definitions_by_id[sector_id]
		var distance := _player.global_position.distance_to(
			Vector3(definition["position"])
		)
		if distance <= load_distance:
			request_sector_load(sector_id)
		elif distance >= unload_distance:
			unload_sector(sector_id)
	_poll_pending_requests()
	_poll_generation_tasks()
	_process_pending_attachments()
	_ensure_cycle_connection()
	_update_sector_ambushes()


func _exit_tree() -> void:
	# Let any in-flight generation finish so worker threads never touch freed
	# state, then discard results that were never added to the tree.
	for task_id in _generation_tasks.values():
		WorkerThreadPool.wait_for_task_completion(task_id)
	_generation_tasks.clear()
	for pending_id in _pending_attachments.keys():
		_discard_pending_attachments(pending_id)
	for sector in _generation_results.values():
		if is_instance_valid(sector):
			sector.free()
	_generation_results.clear()


func request_sector_load(sector_id: StringName) -> bool:
	if (
		_instances.has(sector_id)
		or _request_started_ticks.has(sector_id)
		or _generation_tasks.has(sector_id)
	):
		return false
	var definition := _get_definition(sector_id)
	if definition.is_empty():
		return false
	if String(definition["kind"]) == "scene":
		var request_error := ResourceLoader.load_threaded_request(
			String(definition["scene_path"])
		)
		if request_error != OK:
			push_error(
				"WorldStreamer could not request sector '%s': %s"
				% [sector_id, request_error]
			)
			return false
		_request_started_ticks[sector_id] = Time.get_ticks_msec()
		sector_load_requested.emit(sector_id)
		return true
	sector_load_requested.emit(sector_id)
	_generate_sector(sector_id, definition)
	return true


func unload_sector(sector_id: StringName) -> bool:
	# A background request in flight cannot be cancelled; dropping the entry
	# makes the result be discarded once it finishes.
	_request_started_ticks.erase(sector_id)
	_discard_pending_attachments(sector_id)
	if not _instances.has(sector_id):
		return false
	var sector: Node3D = _instances[sector_id]
	_instances.erase(sector_id)
	if is_instance_valid(sector):
		remove_child(sector)
		sector.queue_free()
	sector_unloaded.emit(sector_id)
	return true


func is_sector_loaded(sector_id: StringName) -> bool:
	return _instances.has(sector_id) and is_instance_valid(_instances[sector_id])


func get_sector(sector_id: StringName) -> Node3D:
	if is_sector_loaded(sector_id):
		return _instances[sector_id]
	return null


func get_loaded_sector_count() -> int:
	var count := 0
	for sector_id in _instances:
		if is_instance_valid(_instances[sector_id]):
			count += 1
	return count


func get_sector_state(sector_id: StringName) -> Dictionary:
	return _sector_states.get(sector_id, {})



func _build_grid_definitions() -> void:
	for grid_x in range(GRID_MIN.x, GRID_MAX.x + 1):
		for grid_z in range(GRID_MIN.y, GRID_MAX.y + 1):
			var coords := Vector2i(grid_x, grid_z)
			if coords == CAMP_COORDS:
				continue
			var sector_position := Vector3(
				coords.x * SECTOR_SIZE, 0.0, coords.y * SECTOR_SIZE
			)
			var sector_id := StringName("sector_%d_%d" % [coords.x, coords.y])
			_definitions_by_id[sector_id] = {
				"id": sector_id,
				"kind": "generated",
				"position": sector_position,
				"coords": coords,
			}


func _generate_sector(sector_id: StringName, definition: Dictionary) -> void:
	# The whole sector subtree is built off the main thread on a worker
	# thread, so the main thread never pays the ~230 ms construction cost.
	var state := _get_or_create_sector_state(sector_id, definition)
	var coords: Vector2i = definition["coords"]
	var sector_position: Vector3 = definition["position"]
	# Painted GridMap cells have to be read here, on the main thread: the worker
	# builds a detached subtree and cannot touch the scene. Without them the
	# sector navmesh would ignore every hand-placed building.
	var painted_obstacles := GridMapObstacles.collect_from_tree(
		get_tree(),
		Rect2(
			sector_position.x - SECTOR_SIZE * 0.5,
			sector_position.z - SECTOR_SIZE * 0.5,
			SECTOR_SIZE,
			SECTOR_SIZE
		),
		sector_position
	)
	var config := {
		"id": sector_id,
		"seed": int(state["seed"]),
		"collected_caches": state["collected_caches"],
		"ammo_collected": bool(state.get("ammo_collected", false)),
		"outer_walls": _get_outer_wall_sides(coords),
		"painted_obstacles": painted_obstacles,
		"label": "SECTOR %d · %d" % [coords.x, coords.y],
		"weapon_collected": bool(state.get("weapon_collected", false)),
		"cache_collected_callable": _on_sector_cache_collected,
		"ammo_collected_callable": _on_sector_ammo_collected,
		"weapon_collected_callable": _on_sector_weapon_collected,
	}
	_generation_meta[sector_id] = {
		"start": Time.get_ticks_usec(),
		"seed": int(state["seed"]),
		"position": Vector3(definition["position"]),
	}
	var task_id := WorkerThreadPool.add_task(
		_build_sector_task.bind(sector_id, config)
	)
	_generation_tasks[sector_id] = task_id


func _build_sector_task(sector_id: StringName, config: Dictionary) -> void:
	# Runs on a worker thread: pure detached-node construction, no tree access.
	var sector := SectorGenerator.build_sector(config)
	_generation_mutex.lock()
	_generation_results[sector_id] = sector
	_generation_mutex.unlock()


func _poll_generation_tasks() -> void:
	for sector_id in _generation_tasks.keys():
		var task_id: int = _generation_tasks[sector_id]
		if not WorkerThreadPool.is_task_completed(task_id):
			continue
		WorkerThreadPool.wait_for_task_completion(task_id)
		_generation_tasks.erase(sector_id)
		_generation_mutex.lock()
		var sector: Node3D = _generation_results.get(sector_id)
		_generation_results.erase(sector_id)
		_generation_mutex.unlock()
		_finalize_generated_sector(sector_id, sector)


func _finalize_generated_sector(sector_id: StringName, sector: Node3D) -> void:
	var meta: Dictionary = _generation_meta.get(sector_id, {})
	_generation_meta.erase(sector_id)
	if sector == null:
		return
	# If the player already moved out of range, drop the freshly built sector.
	if not _definitions_by_id.has(sector_id) or _instances.has(sector_id):
		sector.free()
		return
	sector.position = meta.get("position", Vector3.ZERO)
	_pending_attachments[sector_id] = _detach_sector_contents(sector)
	add_child(sector)
	_instances[sector_id] = sector
	var elapsed_ms := (Time.get_ticks_usec() - int(meta.get("start", 0))) / 1000.0
	last_build_ms = elapsed_ms
	print(
		"WorldStreamer: sector '%s' built on a worker thread in %.1f ms (seed %d)."
		% [sector_id, elapsed_ms, int(meta.get("seed", 0))]
	)
	sector_loaded.emit(sector_id)


func _detach_sector_contents(sector: Node3D) -> Array:
	# Flatten the subtree into an ordered queue (parents before their children)
	# so it can be re-attached in small slices without changing the result.
	var queue: Array = []
	for child in sector.get_children():
		sector.remove_child(child)
		queue.append([sector, child])
		if child.get_child_count() > 3:
			for grandchild in child.get_children():
				child.remove_child(grandchild)
				queue.append([child, grandchild])
	return queue


func _process_pending_attachments() -> void:
	for sector_id in _pending_attachments.keys():
		var queue: Array = _pending_attachments[sector_id]
		var added := 0
		while added < SECTOR_NODES_PER_FRAME and not queue.is_empty():
			var entry: Array = queue.pop_front()
			var parent: Node = entry[0]
			var node: Node = entry[1]
			if is_instance_valid(parent) and is_instance_valid(node):
				parent.add_child(node)
			added += 1
		if queue.is_empty():
			_pending_attachments.erase(sector_id)


func _discard_pending_attachments(sector_id: StringName) -> void:
	if not _pending_attachments.has(sector_id):
		return
	for entry in _pending_attachments[sector_id]:
		var node: Node = entry[1]
		if is_instance_valid(node) and node.get_parent() == null:
			node.free()
	_pending_attachments.erase(sector_id)


func _get_or_create_sector_state(
	sector_id: StringName, definition: Dictionary
) -> Dictionary:
	if not _sector_states.has(sector_id):
		var coords: Vector2i = definition["coords"]
		_sector_states[sector_id] = {
			"seed": hash([_run_seed, coords.x, coords.y]) & 0x7FFFFFFF,
			"collected_caches": [],
			"ammo_collected": false,
			"weapon_collected": false,
			"ambush_triggered": false,
			"ambush_enemies": [],
		}
	return _sector_states[sector_id]


func _get_outer_wall_sides(coords: Vector2i) -> Array[StringName]:
	var sides: Array[StringName] = []
	if coords.x - 1 < GRID_MIN.x:
		sides.append(&"west")
	if coords.x + 1 > GRID_MAX.x:
		sides.append(&"east")
	if coords.y - 1 < GRID_MIN.y:
		sides.append(&"north")
	if coords.y + 1 > GRID_MAX.y:
		sides.append(&"south")
	return sides


func _on_sector_cache_collected(sector_id: StringName, cache_index: int) -> void:
	if not _sector_states.has(sector_id):
		return
	var collected: Array = _sector_states[sector_id]["collected_caches"]
	if cache_index not in collected:
		collected.append(cache_index)
	sector_state_changed.emit(sector_id)


func _on_sector_ammo_collected(sector_id: StringName) -> void:
	if not _sector_states.has(sector_id):
		return
	_sector_states[sector_id]["ammo_collected"] = true
	sector_state_changed.emit(sector_id)


func _on_sector_weapon_collected(sector_id: StringName) -> void:
	if not _sector_states.has(sector_id):
		return
	_sector_states[sector_id]["weapon_collected"] = true
	sector_state_changed.emit(sector_id)


func _ensure_cycle_connection() -> void:
	if _cycle_connected:
		return
	var wave_manager := get_tree().get_first_node_in_group(WAVE_MANAGER_GROUP)
	if wave_manager == null or not wave_manager.has_signal(&"cycle_completed"):
		return
	wave_manager.connect(&"cycle_completed", _on_cycle_completed)
	_cycle_connected = true


func _on_cycle_completed(_cycle_number: int) -> void:
	# Re-arm every sector's ambush; the living-enemy guard in the trigger keeps a
	# fresh wave from stacking on top of one that is still being fought.
	for state in _sector_states.values():
		state["ambush_triggered"] = false


func _update_sector_ambushes() -> void:
	for sector_id in _instances:
		var definition: Dictionary = _definitions_by_id.get(sector_id, {})
		if definition.is_empty() or String(definition["kind"]) != "generated":
			continue
		var state: Dictionary = _sector_states.get(sector_id, {})
		if state.is_empty() or bool(state.get("ambush_triggered", false)):
			continue
		if not _ambush_enemies_cleared(state):
			continue
		var distance := _player.global_position.distance_to(
			Vector3(definition["position"])
		)
		if distance > AMBUSH_TRIGGER_DISTANCE:
			continue
		if _try_spawn_sector_ambush(sector_id, state):
			state["ambush_triggered"] = true
			sector_state_changed.emit(sector_id)


func _ambush_enemies_cleared(state: Dictionary) -> bool:
	var living: Array = state.get("ambush_enemies", [])
	for enemy in living:
		if is_instance_valid(enemy):
			return false
	return true


func _try_spawn_sector_ambush(sector_id: StringName, state: Dictionary) -> bool:
	var wave_manager := get_tree().get_first_node_in_group(WAVE_MANAGER_GROUP)
	if (
		wave_manager == null
		or not wave_manager.has_method(&"spawn_exploration_enemies")
		or not bool(wave_manager.call(&"is_preparation_active"))
	):
		return false
	var sector := get_sector(sector_id)
	if sector == null:
		return false
	var spawns_root := sector.get_node_or_null("SpawnPoints")
	if spawns_root == null:
		return false
	var markers: Array[Marker3D] = []
	for child in spawns_root.get_children():
		var marker := child as Marker3D
		if marker != null:
			markers.append(marker)
	if markers.is_empty():
		return false
	var ambush_seed := int(state["seed"])
	var runner_count := ambush_seed % 2
	var normal_markers := markers.slice(0, markers.size() - runner_count)
	var runner_markers := markers.slice(markers.size() - runner_count)
	var spawned_enemies: Array = []
	if not normal_markers.is_empty():
		spawned_enemies.append_array(wave_manager.call(
			&"spawn_exploration_enemies",
			wave_manager.get(&"normal_zombie_scene"),
			normal_markers
		))
	if not runner_markers.is_empty():
		spawned_enemies.append_array(wave_manager.call(
			&"spawn_exploration_enemies",
			wave_manager.get(&"runner_zombie_scene"),
			runner_markers
		))
	if spawned_enemies.is_empty():
		return false
	state["ambush_enemies"] = spawned_enemies
	var camp_economy := get_tree().get_first_node_in_group(CAMP_ECONOMY_GROUP)
	if camp_economy != null and camp_economy.has_method(&"request_feedback"):
		var coords: Vector2i = _definitions_by_id[sector_id]["coords"]
		camp_economy.call(
			&"request_feedback",
			"AMBUSH IN SECTOR %d · %d" % [coords.x, coords.y]
		)
	return true


func _poll_pending_requests() -> void:
	for sector_id in _request_started_ticks.keys():
		var definition := _get_definition(sector_id)
		var scene_path := String(definition["scene_path"])
		var status := ResourceLoader.load_threaded_get_status(scene_path)
		match status:
			ResourceLoader.THREAD_LOAD_IN_PROGRESS:
				continue
			ResourceLoader.THREAD_LOAD_LOADED:
				var elapsed_ms := (
					Time.get_ticks_msec() - int(_request_started_ticks[sector_id])
				)
				_request_started_ticks.erase(sector_id)
				var sector_scene := ResourceLoader.load_threaded_get(scene_path) as PackedScene
				_instantiate_scene_sector(sector_id, definition, sector_scene, elapsed_ms)
			_:
				_request_started_ticks.erase(sector_id)
				push_error(
					"WorldStreamer failed to load sector '%s' (status %d)." % [sector_id, status]
				)


func _instantiate_scene_sector(
	sector_id: StringName,
	definition: Dictionary,
	sector_scene: PackedScene,
	elapsed_ms: int
) -> void:
	if sector_scene == null:
		push_error("WorldStreamer received an empty scene for sector '%s'." % sector_id)
		return
	var sector := sector_scene.instantiate() as Node3D
	if sector == null:
		push_error("WorldStreamer sector scenes must use a Node3D root.")
		return
	sector.name = String(sector_id).to_pascal_case() + "Sector"
	sector.position = Vector3(definition["position"])
	add_child(sector)
	_instances[sector_id] = sector
	last_build_ms = float(elapsed_ms)
	print("WorldStreamer: sector '%s' ready in %d ms (background)." % [sector_id, elapsed_ms])
	sector_loaded.emit(sector_id)


func _get_definition(sector_id: StringName) -> Dictionary:
	if not _definitions_by_id.has(sector_id):
		push_error("WorldStreamer has no sector definition for '%s'." % sector_id)
		return {}
	return _definitions_by_id[sector_id]


func _find_player() -> void:
	_player = get_tree().get_first_node_in_group(PLAYER_GROUP) as Node3D

